# Link with Mold, and without libc! We use nostartfiles to avoid the C runtime
# See:
#  <https://github.com/rui314/mold?tab=readme-ov-file#how-to-use>
[target.'cfg(target_os = "linux")']
rustflags = [ "-C", "link-arg=-fuse-ld=mold", "-C", "link-arg=-nostartfiles" ]
